// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BookStore
{
    public partial class Users
    {
        public Users()
        {
            Books = new HashSet<Books>();
            Shifts = new HashSet<Shifts>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Position { get; set; }
        public decimal? HourWage { get; set; }

        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<Shifts> Shifts { get; set; }
    }
}