// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BookStore.Data
{
    public partial class Shifts
    {
        public int Id { get; set; }
        public DateTime? Start { get; set; }
        public DateTime? End { get; set; }
        public int? User { get; set; }
        public string Comments { get; set; }

        public virtual Users UserNavigation { get; set; }
    }
}